[project]
name = "splittingpdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pathlib>=1.0.1",
    "pycryptodome>=3.23.0",
    "pypdf2>=3.0.1",
    "pytest>=9.0.2",
]
